### ISSUE TITLE
Load data error

### ISSUE THREAD

**Issue by ChenShuai1981** [aerospike/aerospike-timeseries-demo#1]
My Aerospike server version is Community 3.9.1. The loading data command is "java -jar target/AeroTimeSeries-1.0.jar -o L -t AAPL,IBM -h 127.0.0.1"

---

Loading Data

---

Inserting Data for 16/12/2015 with Primary Key: AAPL1450195200000
Exception: com.aerospike.client.AerospikeException: Error Code 4: Parameter error
com.aerospike.client.AerospikeException: Error Code 4: Parameter error
        at com.aerospike.client.command.ReadCommand.parseResult(ReadCommand.java:121)
        at com.aerospike.client.command.SyncCommand.execute(SyncCommand.java:57)
        at com.aerospike.client.AerospikeClient.operate(AerospikeClient.java:697)
        at com.aerospike.examples.timeseries.TimeSeriesManipulator.updateTimeSeries(TimeSeriesManipulator.java:128)
        at com.aerospike.examples.timeseries.TimeSeriesManipulator.run(TimeSeriesManipulator.java:192)
        at com.aerospike.examples.timeseries.TimeSeriesManipulator.main(TimeSeriesManipulator.java:563)

**Comment by aveekshith** [comment]
You get this parameter error when the version does not support MapOperation. Can you please check if the version you have is certainly 3.9.1. You can check by using asinfo -v 'build'

**Comment by ChenShuai1981** [comment]
Yes, you're right. I found the version of aerospike server is still old 3.7.1 after executed "vagrant box update" command (It saying support CE 3.9.1). So I reinstalled Vagrant box "aerospike/centos-6.5" and now it get updated to 3.9.1 and Testing data was loaded correctly, thank you!
